services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'rentARoom'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'rentARoom'  # Default database that will be created initially
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script to create additional DBs
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: